apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgBBkDiaGABBAKqq36cUl9uf5wK50FDr9wVAJaq5Xm44QUGBimpCDzHTuK+sq0nMGiEE8DhaqJIF8Sf5A6CBGdqqGEjTEtkbUmdSJIvlj8eKJNFvnbXiT249jCmZyeA/ZFj0QH0pGi+74Ep3caqe3jSgr1fKHMfal00UYIoTeAFsStA19aIJkTn9xXvO7kPcD3fTEJfgK3QEE04Upt+rSfaSu0XyJhXhnHUzsNaRCTZvpbXDNa12HO2bW+Usq9K7GWZnuqDcvkpZDSXNo7a4LzCwX2gBretTgcN1wjsJYDCnoAH5KHYMueNsmmXI+NgSe+fkuqJD/3ssFB2mqlk1O+Lv+GFSsgLIzDglyZH/HtWblvvw3GeLpCDy+XqYjmJ2Tn6TMJWhWAYE2WPEGk9eGR+xRwYg+TVHGA0mF8ziKlyUjpcq/RzSJX5PgUzHMKO3ld9obLVlrKSIHreAsqT1FulXQxgfwq5Qn91QB4l8I5Xw138M8OSVTRgMfcosrbUAAuOYesWEaSkFei60+xEsvQMXGmPBs1POiI09EXmHLRPxlFhyjuCR4oUZv9pNLsHDxoFjkLW5jqKzNwRTpgXIcVuyjjbzWciQrIHVocJj+jq46cDjMqzkVa4JHHBfcX2IC692NrTs8lWzpyQhuCUG0MYkSnbNuor5Zq7zfYOebTAMLpaHstUdKrciTQA2CZdTbkWFDwTmJTbYRg==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

